version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tbt
      POSTGRES_PASSWORD: tbt
      POSTGRES_DB: tbt
    ports:
      - 5432:5432 # expose port for Prisma Studio

  apollo-server:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - postgres
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://tbt:tbt@postgres/tbt
