FROM --platform=amd64 node:16-alpine as build
WORKDIR /app
ENV PATH "/app/node_modules/.bin:$PATH"
COPY package.json package-lock.json ./
RUN npm install
COPY prisma ./prisma
RUN npm run generate:prisma
COPY . ./
CMD [ "npm", "run", "dev" ]