# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  local-funcs

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: WherebyLigraphql/build/src/lambdas/wherebyListener.js
  wherebyEvent:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/src/lambdas/wherebyListener.handler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: This function listens for events from whereby.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /wherebyEvent
            Method: POST
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  s3Event:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/src/lambdas/s3Events.handler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: This function listens for events from s3 bucket.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /s3Event
            Method: POST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
